# Generated by Django 2.2.5 on 2019-09-30 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('abrev', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('denom', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=60)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matricula.Curso')),
            ],
        ),
    ]
