# Generated by Django 2.2.5 on 2019-10-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos/'),
        ),
    ]
